<?php
/*
 *    Copyright (C) 2014-2015  Dustin Demuth
 *    Westfälische Wilhelms-Universität Münster
 *    Zentrum für Informationsverarbeitung - CERT
 *    
 *    This program is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 2 of the License, or
 *    (at your option) any later version.
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *    You should have received a copy of the GNU General Public License
 *    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/* 
 * Config
 */

include_once 'openvas_plugin_omp50_commands.php';
include_once 'openvas_plugin_helper.php';
include_once 'openvas_plugin_communicator.php';


$omp_host       ='HOSTNAME';
$omp_port       ='9390';

$omp_new_task_default_comment = "Task generated by certONLINE openvas plugin";
$omp_new_target_default_comment = "Target generated by certONLINE openvas plugin";

/*
 *  To be Configured in GreenboneSecurityAssistant
 */

$omp_username   = 'USERNAME';
$omp_password   = 'PASSWORD';

// The ID of the scanconfig which has to be used
$omp_scanconfig ='ID';
//The ID of the alert which has to receive an e-Mail when a task has finished
$omp_alertid = 'ID';
//The ID of the Portlist which should be used when a new Target is created
$omp_portlistid = 'ID';
$omp_alivetest = 'Scan Config Default';

//The ID of the PDF Format for Reports
$omp_pdf_report_id = 'ID';
